name: SimpleBuild
on: push
jobs:
  build:
    name: Test compiling examples for Arduino UNO
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Compile all examples
      uses: ArminJo/arduino-test-compile@v3
